### ISSUE TITLE
Membrane bound protein preparation

### ISSUE THREAD

**Issue by hamid13r** [carsonpurnell/cryotomosim_CTS#13]
I have been trying to use ctgui to make tomograms for Dragongfly. The basic workflow works great (haven't gone to the dragonfly side yet) but the membrane-bound protein tutorial is very confusing. 

I tried downloading PDB 7JG5 and going through the "membrane stuff tutorial". 
Method one just say delete the dummy atoms and 
select :DUM 
doesn't select any atoms, I did the delete command and saved the cif file but my ATP synthases are randomly dispersed and are not on the membrane. 

When I try making a centeroid or even a submodel named origin_TMD I get this error on the import layer:
```
Error using textscan
First input can not be empty. Expected a non-empty character vector or a valid file-id.

Error in helper_pdb2vol>internal_cifparse (line 131)
    q = textscan([q{:}],'%s','Delimiter',' ','MultipleDelimsAsOne',1); %read strings into cells

Error in helper_pdb2vol (line 33)
        data = internal_cifparse(pdb);

Error in helper_input (line 107)
        [tmp.vol,tmp.sumvol,names] = helper_pdb2vol(list{i},pixelsize,trim,centering,sv);

Error in param_model (line 99)
    layers{i} = helper_input('gui',param.pix); %load layer - how to deal with saved list of layers?

Error in ctsgui/ImportLayersButtonPushed (line 559)
            app.modelparam = param_model(app.PixelSizeangEditField_2.Value, 'density',app.pdensity, ...

Error in appdesigner.internal.service.AppManagementService/executeCallback (line 138)
                callback(appOrUserComponent, event);

Error in matlab.apps.AppBase>@(source,event)executeCallback(appdesigner.internal.service.AppManagementService.instance(),app,callback,requiresEventData,event) (line 63)
            newCallback = @(source, event)executeCallback(appdesigner.internal.service.AppManagementService.instance(), ...
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback
Error while evaluating Button PrivateButtonPushedFcn.
```

Any idea what I am doing  wrong?

Thank you,
Hamid

**Comment by hamid13r** [comment]
Thank you very much. I was going to the OPM database but downloading the wrong pdb (which was just the pdb). 

It works now, I just need to figure out how to make ATPsynthases to got outward on the vesicles instead of inward.

**Comment by carsonpurnell** [comment]
It's just a matter of reversing the model - with Chimera the command flip 180 center 0,0,0 should do the trick if you have not yet found one.

In our experience, the inward/outward orientation actually does not matter in normal circumstances. ATPs is relatively easy to identify from the distinctive head domain, and local membrane curvature does not appear to contribute significantly to segmentation accuracy (for the architectures we use, at least). Outward-facing will help increase placement density though, so making training data could be quite a bit faster.

**Comment by hamid13r** [comment]
yes thanks. I did flip the model and had to move it down a little to get the TMD inside the membrane. 

It is good to know the orientation doesn't matter that much, that was a question I wanted to ask. 

Thank you for your help, I am going to try the dragonfly workflow with adding a real tomogram to this dataset next.
