### ISSUE TITLE
Bug from Ctsgui

### ISSUE THREAD

**Issue by builab** [carsonpurnell/cryotomosim_CTS#14]
Somehow when you use the GUI to simulate a tomogram. Despite putting a pixel size of X Angstrom in the Model part, the generated tomogram will always have a pixel size of 10 Angstrom/Pixel.

**Comment by carsonpurnell** [comment]
Are you using the latest version? this bug was previously identified, and (should have) been fixed in an earlier release.

**Comment by builab** [comment]
Not latest. I saw you fixed that v0.52 now. Thanks, will try again.

**Comment by carsonpurnell** [comment]
Did the newer version resolve the problem?
