### ISSUE TITLE
Converting tiff to mrc and contrast

### ISSUE THREAD

**Issue by hamid13r** [carsonpurnell/cryotomosim_CTS#15]
Hi Carson,

I have denoised some tomogarms in dragonfly and used tif2mrc to convert them to mrc. The problem is some programs (like Cube and Cryolo) show these tomograms white on black. 

To be clear 3dmod, cryolo_boxmanager, and napari show them correctly. But when they are filtered in cryolo they show up inverted. Any ideas what could be happening here?

Best,
Hamid

**Comment by carsonpurnell** [comment]
Just to be clear - there's nothing amiss with any CTS outputs or conversions from them?

**Comment by hamid13r** [comment]
No, the tomograms coming out of CTS look great. I was hoping you know a better way to convert them so this problem wont occur. 

Update: Apparently if I use `clip flipx -m 2` the problem goes away. So it is something about the way tif2mrc saves the data.

**Comment by carsonpurnell** [comment]
You must be using a data type that those other programs do not handle properly. just output a more complex mode like float or 16 bit signed.
