### ISSUE TITLE
Possibility to simulate VPP tomograms

### ISSUE THREAD

**Issue by frosinastojanovska** [carsonpurnell/cryotomosim_CTS#16]
Hello, is there a possibility of simulating the VPP effect with an added phase shift to the defocus? 

I already created a large dataset of hundreds of tomograms to train the DL models I was developing. Yet, in the real dataset, I find tomograms imaged with VPP, and I need simulations that can also help identify the accuracy of the different versions of tomograms (only defocus or defocus + phase shift). Let me know what you think about this :).

**Comment by carsonpurnell** [comment]
I am interested in getting phase contrast working, but I do not myself use it. Would you be able to send me a handful of example tomograms of each, and your imaging conditions? Most of the necessary backend already exists, I just need to properly calibrate and provide access to its parameters. Proper data will help with that.

**Comment by frosinastojanovska** [comment]
Hi @carsonpurnell, this can be a nice dataset for VPP, since it has the same sample imaged with only defocus and with VPP: https://www.ebi.ac.uk/empiar/EMPIAR-10988/

**Comment by carsonpurnell** [comment]
I've published a new release version with very basic phase contrast support. the simulation parameter is 'phase' and input value in radians. the contrast spectra looks reasonable, but the SNR and resolution is not accurate out of the box. You will need to manually adjust other parameters, especially dose, to get a more realistic simulation if you run at pi/2 phase. Let me know how it works out, and how it compares to your datasets for later improvements.

**Comment by carsonpurnell** [comment]
@frosinastojanovska have you tested the VPP functionality? I'm interested to hear your feedback.
