### ISSUE TITLE
error(['in ReadMRC the file could not be opened: ' filename])

### ISSUE THREAD

**Issue by MoritzWM** [carsonpurnell/cryotomosim_CTS#5]
Hello!
I wanted to try the CTS simulate step, but I get the following error when clicking the "Generate Files" button from the ctsgui:

```
Session folder: sim_dose_100_vrnp_1
xyzproj -axis Y -width 1023 -tiltfile tiltangles.txt 0_model_fix_4BBL_vrnp_1.mrc 1_tilt_fix_4BBL_vrnp_1.mrc
Error using error
The message must be specified as either a character vector, string scalar, or a message structure.

Error in ReadMRC (line 77)
    error(['in ReadMRC the file could not be opened: ' filename])

Error in cts_simulate>internal_sim (line 122)
tilt = ReadMRC(prev); %load the projected tiltseries as a volume

Error in cts_simulate (line 83)
[detected, conv, tiltseries, ctf] = internal_sim(vol,filename,param,'real');

Error in ctsgui/GenerateFilesButtonPushed (line 387)
         cts_simulate(app.path, app.param, 'suffix', app.SuffixTextArea.Value);

Error in appdesigner.internal.service.AppManagementService/executeCallback (line 138)
                callback(appOrUserComponent, event);

Error in matlab.apps.AppBase>@(source,event)executeCallback(appdesigner.internal.service.AppManagementService.instance(),app,callback,requiresEventData,event) (line 63)
            newCallback = @(source, event)executeCallback(appdesigner.internal.service.AppManagementService.instance(), ...
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback
Error while evaluating Button PrivateButtonPushedFcn.
```

I created the model from the GUI and it looks like it worked. Then, I imported the model in the GUI and used the standard parameters.

**Comment by carsonpurnell** [comment]
Can you attach the model .mat file (should be in your home directory, in the tomosim folder)? I'll try to run it myself to troubleshoot. Could be an issue with the size of the mrc.

Also, are you using a mac? If so, you need to start matlab from the command line, not from a shortcut. This is one of the failure points for macs.

**Comment by MoritzWM** [comment]
Hi, thanks that fixed it!
I created the model with the same dimensions as my tomogram, 1023x1440x100 pixels. Seems that was too big. 400x600x100 works fine, though. Thanks a lot!

**Comment by carsonpurnell** [comment]
I've run a simulation with no problem. Can you verify your IMOD installation? Run 'header *.mrc' in the simulation folder where the error occurred - there should be a 0_model.mrc in there at least.

**Comment by MoritzWM** [comment]
Looks like the IMOD installation was at fault. When starting from the desktop link, Matlab doesn't source the .bashrc in my case. From the terminal all is fine...
So no bug in the end!
