### ISSUE TITLE
Problem with parameter in cts_simulate

### ISSUE THREAD

**Issue by frosinastojanovska** [carsonpurnell/cryotomosim_CTS#6]
Hello :), 

While trying to simulate a tomogram, I encountered the following error while executing the `cts_simulate` function with the previously generated .mat file: 

```
Unrecognized field name "pix".

Error in helper_particleatlas (line 47)
        WriteMRC(bin,cts.pix,append(filename,'.mrc'))

Error in cts_simulate (line 86)
    atlas = helper_particleatlas(cts,opt.atlasindividual,opt.dynamotable);
```

I fixed it for myself by changing `cts.pix` into `cts.param.pix` in the helper_particleatlas.m file, but maybe you have another way, so I'm opening this issue :). 

Best,
Frosina

**Comment by carsonpurnell** [comment]
No, that's the right fix. Newest version should be patched.
